<a href="https://colab.research.google.com/github/ishancoderr/Landslide_-Identifier/blob/main/Landslide_identifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.scirp.org/journal/paperinformation.aspx?paperid=81276


https://en.climate-data.org/asia/sri-lanka/uva/badulla-764256/

https://books.google.lk/books?id=L3ckDwAAQBAJ&pg=PA270&lpg=PA270&dq=rainfall+data+with+cumulative+time+in+badulla&source=bl&ots=3YCsce_9-A&sig=ACfU3U1hUHgX5JoFKeC2LIYimb4GFj_CsA&hl=en&sa=X&ved=2ahUKEwjyy9av1aHzAhVBjeYKHXS_DAkQ6AF6BAglEAM#v=onepage&q=rainfall%20data%20with%20cumulative%20time%20in%20badulla&f=false

**Importing the libraries**

In [308]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Importing Rainfall data** 

In [309]:
dataset = pd.read_csv('/content/sample_data/Rainfall.csv')

In [310]:
dataset.head()

Year     Month  Day  ...  Duration (hr)  Avg_intensity (mm/hr)  occur
0  1997  November   17  ...            6.0                     43    yes
1  1997  November   19  ...            5.0                     53    yes
2  1997  November   19  ...            6.0                     48    yes
3  1997  November   19  ...            4.0                     54    yes
4  1998  November   16  ...            3.0                     50    yes

[5 rows x 7 columns]

In [311]:
column_names=dataset.columns.values.tolist()
print(column_names)

['Year', 'Month', 'Day', 'Avg_Accumulation (mm)', 'Duration (hr)', 'Avg_intensity (mm/hr)', 'occur']


**import Encoders**

In [312]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [313]:
labelencode=LabelEncoder()
dataset['occur_']=labelencode.fit_transform(dataset['occur'])
labelencode=LabelEncoder()
dataset['Month_']=labelencode.fit_transform(dataset['Month'])
labelencode=LabelEncoder()

In [314]:
dataset.head()

Year     Month  Day  ...  occur  occur_  Month_
0  1997  November   17  ...    yes       1       9
1  1997  November   19  ...    yes       1       9
2  1997  November   19  ...    yes       1       9
3  1997  November   19  ...    yes       1       9
4  1998  November   16  ...    yes       1       9

[5 rows x 9 columns]

**Make new data frame with this dataset**

In [315]:
new_dataset= dataset[[ 'Avg_Accumulation (mm)', 'Duration (hr)', 'Avg_intensity (mm/hr)', 'occur_']]

In [316]:
new_dataset.head()

Avg_Accumulation (mm)  Duration (hr)  Avg_intensity (mm/hr)  occur_
0                    257            6.0                     43       1
1                    268            5.0                     53       1
2                    289            6.0                     48       1
3                    215            4.0                     54       1
4                    149            3.0                     50       1

**splitting the dataset into Test set and Training set**

In [317]:
x=new_dataset.iloc[:,:-1].values 
y=new_dataset.iloc[:,-1].values

In [318]:
print(x)
print(y)

[[257.    6.   43. ]
 [268.    5.   53. ]
 [289.    6.   48. ]
 [215.    4.   54. ]
 [149.    3.   50. ]
 [180.    4.   45. ]
 [206.    5.   41. ]
 [211.    5.   42. ]
 [320.    6.   53. ]
 [307.    7.   44. ]
 [338.    8.   42. ]
 [316.    7.   45. ]
 [199.    5.   40. ]
 [189.    4.   47. ]
 [160.    3.   53. ]
 [221.    6.   37. ]
 [160.    3.   53. ]
 [306.    6.   51. ]
 [174.    4.   44. ]
 [149.    4.   37. ]
 [189.    5.   38. ]
 [107.    3.   36. ]
 [149.    4.   37. ]
 [139.    5.5  25. ]
 [141.    5.6  25. ]
 [112.    4.   28. ]
 [ 54.    2.1  25. ]
 [130.    6.   28. ]
 [ 73.    3.   24. ]
 [140.    5.   28. ]
 [130.    5.   26. ]
 [109.    6.   18. ]
 [ 90.    3.   30. ]
 [ 88.    4.   22. ]
 [ 52.    2.   26. ]
 [ 74.    3.   27. ]
 [ 50.    1.5  33. ]
 [ 80.    3.   27. ]
 [120.    4.   30. ]
 [134.    4.   31. ]
 [197.    5.   39. ]
 [205.    5.   41. ]
 [165.    4.   41. ]
 [319.    7.   46. ]
 [305.    7.   44. ]
 [310.    6.   52. ]
 [179.    4.   45. ]
 [198.    8. 

In [319]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75,test_size=0.25,random_state=0)

In [320]:
print(x_train)
print(y_train)

[[ 52.    2.   26. ]
 [174.    4.   44. ]
 [211.    5.   42. ]
 [160.    3.   53. ]
 [310.    6.   52. ]
 [212.    4.   53. ]
 [140.    5.   28. ]
 [221.    6.   37. ]
 [130.    5.   26. ]
 [ 90.    3.   30. ]
 [160.    3.   53. ]
 [165.    4.   41. ]
 [189.    5.   38. ]
 [319.    7.   46. ]
 [320.    6.   53. ]
 [189.    4.   47. ]
 [112.    4.   28. ]
 [180.    4.   45. ]
 [306.    6.   51. ]
 [197.    5.   39. ]
 [228.    5.   46. ]
 [268.    5.   53. ]
 [199.    5.   40. ]
 [ 80.    3.   27. ]
 [141.    5.6  25. ]
 [206.    5.   41. ]
 [139.    5.5  25. ]
 [ 50.    1.5  33. ]
 [107.    3.   36. ]
 [149.    4.   37. ]
 [307.    7.   44. ]
 [134.    4.   31. ]
 [179.    4.   45. ]
 [215.    4.   54. ]
 [257.    6.   43. ]
 [198.    8.   25. ]
 [305.    7.   44. ]]
[0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 0 0 1 1 1 0 1 1 1 1 1]


In [321]:
print(x_test)
print(y_test)


[[ 73.    3.   24. ]
 [316.    7.   45. ]
 [338.    8.   42. ]
 [205.    5.   41. ]
 [289.    6.   48. ]
 [130.    6.   28. ]
 [120.    4.   30. ]
 [109.    6.   18. ]
 [149.    4.   37. ]
 [149.    3.   50. ]
 [ 88.    4.   22. ]
 [ 74.    3.   27. ]
 [ 54.    2.1  25. ]]
[0 1 1 1 1 0 0 0 1 1 0 0 0]


# Train Logistic Regression model on Training set

In [322]:
from sklearn.linear_model import LogisticRegression
Classifier=LogisticRegression(random_state=0)
Classifier.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

# predicting new result

In [323]:
print(Classifier.predict(sc.transform([[ 180,    4,  45]])))

[0]


**Predicting the Test set results**

In [324]:
y_pred = Classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]]


# Making the Confusion Matrix

In [325]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[7 0]
 [0 6]]


1.0